[package]
name = "ultrafast-mcp-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Transport layer implementation for UltraFast MCP"

# docs.rs configuration
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
ultrafast-mcp-core = { path = "../ultrafast-mcp-core" }
ultrafast-mcp-auth = { path = "../ultrafast-mcp-auth", optional = true }
tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["codec"] }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = "0.1"
async-trait = { workspace = true }
bytes = "1.0"
uuid = { version = "1.0", features = ["v4"] }
thiserror = { workspace = true }
anyhow = { workspace = true }

# HTTP transport dependencies
# HTTP transport dependencies
axum = { workspace = true, optional = true }
tokio-stream = { version = "0.1", features = ["sync"], optional = true }
tower-http = { workspace = true, features = ["cors"], optional = true }
tower = { workspace = true, features = ["util"], optional = true }
reqwest = { workspace = true, optional = true }
hyper = { version = "1.0", optional = true }
hyper-util = { version = "0.1", features = ["tokio"], optional = true }

[features]
default = ["stdio"]
stdio = []
http = [
    "dep:axum", 
    "dep:tokio-stream", 
    "dep:tower-http", 
    "dep:tower", 
    "dep:reqwest", 
    "dep:hyper", 
    "dep:ultrafast-mcp-auth"
]
