[package]
name = "ultrafast-mcp-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"
description = "Transport layer implementation for UltraFast MCP"

# docs.rs configuration
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Internal dependencies
ultrafast-mcp-core = { path = "../ultrafast-mcp-core", version = "202506018.1.0-rc.1.6" }
ultrafast-mcp-auth = { path = "../ultrafast-mcp-auth", version = "202506018.1.0-rc.1.6", optional = true }

# Core runtime dependencies
tokio = { workspace = true }
tokio-util = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }

# HTTP transport dependencies
axum = { workspace = true, optional = true }
tokio-stream = { workspace = true, optional = true }
tower-http = { workspace = true, features = ["cors", "compression-gzip", "compression-deflate"], optional = true }
tower = { workspace = true, features = ["util"], optional = true }
reqwest = { workspace = true, optional = true }
hyper = { workspace = true, optional = true }
hyper-util = { workspace = true, optional = true }

[features]
default = ["stdio"]
stdio = []
http = [
    "dep:axum", 
    "dep:tokio-stream", 
    "dep:tower-http", 
    "dep:tower", 
    "dep:reqwest", 
    "dep:hyper", 
    "dep:hyper-util",
    "dep:ultrafast-mcp-auth"
]
full = ["http"]

[dev-dependencies]
tokio-test = { workspace = true }
tempfile = { workspace = true }
