[package]
name = "ultrafast-mcp-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Authentication and authorization for ULTRAFAST MCP"

[dependencies]
ultrafast-mcp-core = { path = "../ultrafast-mcp-core" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }

# OAuth 2.1 dependencies
oauth2 = { workspace = true }
jsonwebtoken = { workspace = true }
base64 = { workspace = true }
url = "2.0"
rand = "0.8"
sha2 = "0.10"

# HTTP client for token requests
reqwest = { workspace = true }

# Tracing
tracing = "0.1"
urlencoding = "2.1.3"

[features]
default = ["oauth"]
oauth = []
